### ISSUE TITLE
Feature: Create lesson plan using AI

### ISSUE THREAD

**Issue by drussell1974** [drussell1974/cssow#735]
**Models**

- [x] Create and test model
- [x] Create and test dbmodel

**Database**

_Create schemas_

- [x] Update sow_lesson_plan with text field
- [x] Create relationship

_Create stored procedures:_

- [x] lesson_plan__get
- [x] lesson_plan__get_all
- [x] lesson_plan__insert
- [x] lesson_plan__update
- [x] lesson_plan__publish_item
- [x] lesson_plan__delete
- [x] lesson_plan__delete_all
- [x] lesson_plan__delete_unpublished

**UI**

- [x] create page with textarea
- [x] show objectives rubric - link to select objectives/or update for schedule
- [x] show lesson summary with checkbox to feed AI
- [x] button to request AI assistance
- [x] option to include tasks ideas (add checkbox and save)
- [x] option to include assessment ideas (add checkbox and save)
- [x] save result
- [x] edit

**Scenarios**

- [x] #736
- [x] #737
- [x] #692

**Additional Features**

- [x] create option for default schedule #738

- [x] #742 - objectives blank if no schedule (do not allow for lessons)
- [x] #743 - prevent generate plan if no learning objectives - currently raises custom exception

**Comment by drussell1974** [comment]
Further enhancements with react app
