### ISSUE TITLE
Fix: Show all scheduled lessons on calendar

### ISSUE THREAD

**Issue by drussell1974** [drussell1974/cssow#822]
- [x] default all schedule lessons - see #836 for further enhancements
- [x] add scheme of work options dropdown - #831 Change SOW from title and Profile from all profles
- [x] #823 Remove calendar and stack buttons 
-
![Schedule](https://github.com/drussell1974/cssow/assets/20655356/0560dc92-d779-4766-8d86-998ae8501ec5)
